namespace: purestorage
name: array
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  purestorage.common: '>=1.0'
repository: git@github.com:ansible-collection-migration/purestorage.array.git
documentation: https://github.com/ansible-collection-migration/purestorage.array/tree/master/docs
homepage: https://github.com/ansible-collection-migration/purestorage.array
issues: https://github.com/ansible-collection-migration/purestorage.array/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
